:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Changelog
All notable changes to this project from 2022-10-21 onward will be documented in this file.

The format is loosely based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog], and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

toc::[]

== Planned for a future release
=== Breaking

== Unreleased
These changes are merged into the `main` branch, but have not been released. After merging pull requests (PRs) that are not immediately released into `main`, a tag is added appending the PR# to the current release. For example, if the release version/tag is `3.2.1`, and PR# 107 is merged without a new release, the state of the codebase after that merge will be tagged as `3.2.1.107`.

=== Breaking

=== Added

=== Changed

=== Bugfixes
* Disabled forms no longer contribute their fields to a record type's field list. (PR#103)

=== Deleted

=== Deprecated/Will break in a future version

== Releases

=== 1.10.0 - 2022-10-21

==== Added
* `ccu debug check_xpath_depth` command
