:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Changelog
All notable changes to this project from 2022-10-21 onward will be documented in this file.

The format is loosely based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog], and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

toc::[]

== Planned for a future release
=== Breaking

== Unreleased
These changes are merged into the `main` branch, but have not been released. After merging pull requests (PRs) that are not immediately released into `main`, a tag is added appending the PR# to the current release. For example, if the release version/tag is `3.2.1`, and PR# 107 is merged without a new release, the state of the codebase after that merge will be tagged as `3.2.1.107`.

=== Breaking

=== Added

=== Changed

* The `version` property in mapper config and mapper_manifest entries is now formatted as "10.0.0" instead of "10-0-0"

=== Bugfixes

=== Deleted

=== Deprecated/Will break in a future version

== Releases

=== 3.1.1 - 2025-02-07

==== Bugfixes

* Gemfile.lock updated with new untangler version

=== 3.1.0 - 2025-02-06

==== Warning

* Application may not work with Ruby versions earlier than 3.2. (PR#161)

==== Added

* Automated download, rename, and reformat of community-supported profile configs (PR#152)
* `mappers digest` command
* Validation of key signatures in form props, and logging (as errors) of unknown key signatures
* `ccu vocabs all` command (leveraging REST API connections) with stdout or csv output
* `ccu vocabs duplicate_terms` command (leveraging REST API connections) with stdout or csv output
* `ccu vocabs duplicate` command (leveraging REST API connections) with stdout or csv output
* Ability connect to community-supported profile REST API by default, and configure REST API connections for other profiles
* Mappers, manifest, templates for OHC 2.0.0 / 20240521
* New UI label lookup table reference report
* Community-supported profile configs, mappers, mapper manifest, CSV templates, and reference documents for 8.1 release

==== Changed

* Friendly fields CSV format now includes field machine name qualified via namespace, and CSV Importer template headers for the field
* `data_source` column in reference reports split into `data_source_type` (e.g. authority, vocabulary, and option list) and `data_source_name` values.
* Community-supported profile configs, mappers, mapper manifest, CSV templates, and reference documents for 8.0 release (fixed, except for UI path issue)
* CLI interface and options more standardized via shared options (PR#152)

==== Bugfixes

* Remove unnecessary/redundant class options on commands in `CCU::Cli::Profiles`
* Stop `CCU::UpgradeWarner` from emitting duplicate warnings
* Fix variable names in `CCU::Fields::Field`
* Do not write unused authority report CSV to an .rb file 🤣
* Detect/log more field definition/form field mismatch issues and fix them.

=== 3.0.0 - 2024-05-14
==== Breaking
* Fields controlled by a single authority vocabulary no longer have simplified header/column names. `default_single_authority_plain_last_versions` has been added in `lib/cspace_config_untangler.rb` and records the last UI config version of known/directly supported by Lyrasis profiles that will have simplified header/column names. This may need to be updated if you are using the Untangler for other profiles.
** The main thing to be concerned with here is that the CSV templates you use are generated with the same header/column names as the mappers you use in the CSV Importer or other tooling

==== Added

* Community-supported profile configs, mappers, mapper manifest, CSV templates, and reference documents for 8.0 release
* Handling of new field definition override pattern in form definition (show only one field from repeatable field group, and make it non-repeatable, materials_4-0-0 objectCount field)
* CLI commands
** forms subpaths
** forms props_type
** forms props_key_sigs

==== Changed

* Upgrade-related warnings now generated by a class that emits each warning only once per run
* Log more info/oddness

==== Bugfixes

* Fix bug in writing fields CSV when there is no value for a field (PR#133)

==== Dev/Internal
* Implement almost-standard for code formatting/style/linting
* Add Github workflow to run tests and lint on PRs
* Remove code obviated by fixes in CollectionSpace 8.0
* Major refactor of code that extracts field data from forms
* Update dependencies; remove unused dependencies

=== 2.0.1 - 2023-10-03
==== Bugfixes

* Fix bug in extraction of search_path for authorities (affected chronology, organization, location)

=== 2.0.1 - 2023-09-19
==== Bugfixes
* Fix failure in `ProfileComparison` class and add integration test

=== 2.0.0 - 2023-08-16
==== Breaking
* `ccu fields csv` command no longer allows you to specify record types to include. All record types from the given profiles are included in the output, which you can easily filter to the record type(s) of interest.
* `explode` is no longer a valid `--structured_date` option value for the `ccu fields csv` command. It has been replaced by `expanded`, which results in the same output as `explode`, which is still the default. Likewise, the `collapse` option has been replaced by `collapsed`

==== Added
* `ccu profiles switch_release` command
* Several commands organized under `ccu authorities` (do `ccu authorities` for the list)
* `ccu fields nonunique_field_names` command
* `--output_mode`/`-m` option for `ccu fields csv` command. Defaults to `expert`, which maintains the same behavior. Can also be set to `friendly`, to generate reports less frightening to users who primarily work in the UI.
* Several new report generators:
** `AuthorityVocabUse`
** `NonuniqueFieldNames`
** `NonuniqueFieldPaths`
** `QaAllFields`
** `QaChangedFields`
** `QaDeletedFields`
** `UnusedAuthorityVocabs`
** `XpathDepthCheck`
* Auto-splitting of user-facing reference reports into single-profile reports organized by profile
* `ccu reports qa` command - generate all QA related reports for a new release

==== Bugfixes
* Resolved issues extracting ui_path and ui_field_label for various fields


=== 1.11.0 - 2022-11-22
==== Bugfixes
* CLI: `-p all` flag no longer errors if no profile in configs directory matches main profile (PR#106)
* Disabled forms no longer contribute their fields to a record type's field list. (PR#103)

==== Added
* Configs and mappers for 7.1 release
* `ccu reports ref` command to generate reference documents for a given release
* `ccu forms disabled` command (PR#104)

==== Changed
* Reorganizes reference documents (all fields CSVs, etc.) into `data/reference` directory, organized by release

=== 1.10.0 - 2022-10-21

==== Added
* `ccu debug check_xpath_depth` command
