:toc:
:toc-placement!:
:toclevels: 4

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= Changelog
All notable changes to this project from 2022-10-21 onward will be documented in this file.

The format is loosely based on https://keepachangelog.com/en/1.0.0/[Keep a Changelog], and this project adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning].

toc::[]

== Planned for a future release
=== Breaking

== Unreleased
These changes are merged into the `main` branch, but have not been released. After merging pull requests (PRs) that are not immediately released into `main`, a tag is added appending the PR# to the current release. For example, if the release version/tag is `3.2.1`, and PR# 107 is merged without a new release, the state of the codebase after that merge will be tagged as `3.2.1.107`.

=== Breaking

=== Added

=== Changed

=== Bugfixes

=== Deleted

=== Deprecated/Will break in a future version

== Releases

=== 2.0.0 - 2023-08-16
==== Breaking
* `ccu fields csv` command no longer allows you to specify record types to include. All record types from the given profiles are included in the output, which you can easily filter to the record type(s) of interest.
* `explode` is no longer a valid `--structured_date` option value for the `ccu fields csv` command. It has been replaced by `expanded`, which results in the same output as `explode`, which is still the default. Likewise, the `collapse` option has been replaced by `collapsed`

==== Added
* `ccu profiles switch_release` command
* Several commands organized under `ccu authorities` (do `ccu authorities` for the list)
* `ccu fields nonunique_field_names` command
* `--output_mode`/`-m` option for `ccu fields csv` command. Defaults to `expert`, which maintains the same behavior. Can also be set to `friendly`, to generate reports less frightening to users who primarily work in the UI.
* Several new report generators:
** `AuthorityVocabUse`
** `NonuniqueFieldNames`
** `NonuniqueFieldPaths`
** `QaAllFields`
** `QaChangedFields`
** `QaDeletedFields`
** `UnusedAuthorityVocabs`
** `XpathDepthCheck`
* Auto-splitting of user-facing reference reports into single-profile reports organized by profile
* `ccu reports qa` command - generate all QA related reports for a new release

==== Bugfixes
* Resolved issues extracting ui_path and ui_field_label for various fields


=== 1.11.0 - 2022-11-22
==== Bugfixes
* CLI: `-p all` flag no longer errors if no profile in configs directory matches main profile (PR#106)
* Disabled forms no longer contribute their fields to a record type's field list. (PR#103)

==== Added
* Configs and mappers for 7.1 release
* `ccu reports ref` command to generate reference documents for a given release
* `ccu forms disabled` command (PR#104)

==== Changed
* Reorganizes reference documents (all fields CSVs, etc.) into `data/reference` directory, organized by release

=== 1.10.0 - 2022-10-21

==== Added
* `ccu debug check_xpath_depth` command
