= UI Config Notes
:toc:
:toclevels: 3

NOTE: Cross-references in this document appear to be broken, and are on the list to fix when I have more time.

== Definitions

form field::
  A field placed in a form template. We use the list of fields actually
  defined in forms/templates for record types in a profile to determine
  (1) the fields actually used in the profile; and (2) the UI path (the
  display messages for panels, input tables, etc. leading to the field).
  We need to look at form fields for #1 because many fields are defined
  in the profile's `+config/recordTypes/{rectypename}/fields+` section
  via inheritance, but not placed in any forms. This is indeed a pattern
  for suppressing fields.

== Form templates

Each form is defined in
`+config/recordTypes/{rectypename}/forms/{formname}/template+`. Each
form definition is a hideous mess of JSON nested in such a way that it
is extremely cumbersome to work with and difficult to understand.

This section captures info about patterns in and handling of form
template config, as of CollectionSpace v8.0

=== Key signatures used in props

The Untangler makes determination of how to process props objects in a
form template based on the keys included in the props object.

[cols=",,",options="header",]
|===
|ct |key signature |treatment
|17279 |["_owner", "key", "props", "ref"] |process props

|9172 |["name"] |capture

|4139 |["children", "name"] |capture; iterate children

|3059 |["children"] |iterate children

|429 |["children", "collapsed", "collapsible", "name"] |capture; iterate
children

|302 |["name", "subpath"] |capture

|286 |["children", "collapsible", "name"] |capture; iterate children

|113 |["children", "name", "subpath"] |capture; iterate children

|15 |["_owner", "key", "props", "ref", "type"] |process props

|10 |["children", "subpath", "tabular"] |capture; iterate children

|9 |["name", "showDetachButton"] |ignore

|8 |["multiline", "name"] |capture

|5 |["embedded", "label", "name"] |capture

|3 |["children", "name", "tabular"] |capture; iterate children

|1 |["style"] |ignore

|1 |["children", "style"] |iterate children

|1 |["defaultMessage", "id", "values"] |ignore


|1 |["children", "labelMessage", "name"] | capture; extract message; iterate children

|1 |["children", "labelMessage", "name", "subpath"] | capture; extract message; iterate children

|? |["children", "name", "subpath", "tabular"] |when name is a namespace and subpath is empty: capture name as namespace; iterate children
|===

The key signatures and counts shown above can be generated by running:

[source,shell]
----
ccu forms props_key_sigs -p all
----

The same command can be used to view examples for a given key signature,
as shown in the examples below.

[source,shell]
----
ccu forms props_key_sigs -p all -k _owner key props ref -e true
----

Do `+ccu forms help props_key_sigs+` for details on command usage.

==== _owner, key, props, ref

Description/understanding::
  A wrapper around a grouping of fields or a single field, for display
  only. That is, there is nothing in this `+props+` object itself that
  we care about in the data layer.
Treatment detail::
  Process the contained `+props+` object with this one as the parent (to
  facilitate inheritance of namespace, xpath, and ui path information)

....
<#CspaceConfigUntangler::Forms::Props:4110 core_9-0-0 / acquisition / default form / panel.acquisition.info / >
{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionReferenceNumber"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"accessionDateGroup"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionAuthorizer", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionAuthorizer"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionAuthorizerDate"}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionDateGroupList", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionDateGroup"}, "_owner"=>nil}}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionMethod"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionSources", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionSource"}, "_owner"=>nil}}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"owners", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"owner"}, "_owner"=>nil}}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"transferOfTitleNumber"}, "_owner"=>nil}]}, "_owner"=>nil}
....

....
<#CspaceConfigUntangler::Forms::Props:4204 core_9-0-0 / acquisition / default form / panel.acquisition.info / >
{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionAuthorizer", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionAuthorizer"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionAuthorizerDate"}, "_owner"=>nil}]}, "_owner"=>nil}
....

....
<#CspaceConfigUntangler::Forms::Props:4134 core_9-0-0 / acquisition / default form / panel.acquisition.info / >
{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"acquisitionReferenceNumber"}, "_owner"=>nil}
....

==== name

Description/understanding::
  Defines a single field. Technically, this may include structured date
  groups, but those are generally treated like a single field for the
  purposes of the Untangler. For example, the assumption is that,
  generally, a user will provide one value (that becomes the
  `+dateDisplayDate+` string) for a "field" like `+accessionDateGroup+`,
  and the `+collectionspace-mapper+` handles exploding that out into all
  relevant structured date detail fields.
Treatment detail::
  Captured as a *form field*. Inherits namespace from parent. Iterative
  processing terminates.

....
<#CspaceConfigUntangler::Forms::Props:4064 core_9-0-0 / acquisition / default form / panel.acquisition.info / accessionDateGroup>
{"name"=>"accessionDateGroup"}


<#CspaceConfigUntangler::Forms::Props:4110 core_9-0-0 / acquisition / default form / panel.acquisition.info / inputTable.acquisition.acquisitionAuthorizer / acquisitionAuthorizer>
{"name"=>"acquisitionAuthorizer"}
....

==== multiline, name

Description/understanding::
  Defines a single field that displays as a multiline text box. Currently
  only present on the `+annotationNote+` field in the OHC profile.
Treatment detail::
  Captured as a *form field*. Inherits namespace from parent. Iterative
  processing terminates.

....
<#CspaceConfigUntangler::Forms::Props:3530 ohc_2-0-0-20240521 / collectionobject / default form / panel.collectionobject.id / collectionobjects_annotation.annotationGroupList / collectionobjects_annotation.annotationGroup / annotationNote>
{"name"=>"annotationNote", "multiline"=>true}
....

[#children-name]
==== children, name

Description/understanding::
  A named grouping in the form. This may be a top-level document, panel,
  input table, or a semantic field grouping.
Treatment detail::
  If we determine the named grouping is a labeled (with a message)
  panel, input table, or semantic field grouping, capture the name as
  part of the UI path. If we determine the named grouping is a semantic
  field grouping, capture name as part of the xpath. Iterate through
  children, passing this `+props+` object as parent to each child.

A panel:

....
<#CspaceConfigUntangler::Forms::Props:5120 lhmc_7-0-0 / acquisition / default form / panel.acquisition.info / panel.acquisition.priceInformation / priceInformation>
{"name"=>"priceInformation", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"groupPurchasePrice", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"groupPurchasePriceCurrency"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"groupPurchasePriceValue"}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"objectPurchasePrice", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"objectPurchasePriceCurrency"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"objectPurchasePriceValue"}, "_owner"=>nil}]}, "_owner"=>nil}]}
....

A semantic field grouping:

....
<#CspaceConfigUntangler::Forms::Props:5024 core_9-0-0 / acquisition / default form / panel.acquisition.info / acquisitions_common.owners / owners>
{"name"=>"owners", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"owner"}, "_owner"=>nil}}

<#CspaceConfigUntangler::Forms::Props:5524 core_9-0-0 / citation / default form / panel.citation.info / citations_common.citationTermGroupList / citations_common.citationTermGroup / inputTable.citation.termSource / termSource>
{"name"=>"termSource", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termSource"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termSourceDetail"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termSourceID"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termSourceNote"}, "_owner"=>nil}]}
....

==== children

Description/understanding::
  A wrapper around a grouping of fields or a single field, for display
  only. That is, there is nothing in this `+props+` object itself that
  we care about in the data layer.
Treatment detail::
  Process the objects under `+children+` with this one as the parent (to
  facilitate inheritance of namespace, xpath, and ui path information)

....
<#CspaceConfigUntangler::Forms::Props:5120 core_9-0-0 / acquisition / default form / panel.acquisition.objectCollectionInformation / childHolder>
{"children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"fieldCollectionEventNames", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"fieldCollectionEventName"}, "_owner"=>nil}}, "_owner"=>nil}}

<#CspaceConfigUntangler::Forms::Props:5170 core_9-0-0 / citation / default form / panel.citation.info / citations_common.citationTermGroupList / citations_common.citationTermGroup / childHolder>
{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termDisplayName"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termStatus"}, "_owner"=>nil}]}

<#CspaceConfigUntangler::Forms::Props:5214 core_9-0-0 / citation / default form / panel.citation.info / citations_common.citationTermGroupList / citations_common.citationTermGroup / childHolder>
{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termType"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termFlag"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termLanguage"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termPrefForLang"}, "_owner"=>nil}]}

<#CspaceConfigUntangler::Forms::Props:5240 core_9-0-0 / citation / default form / panel.citation.info / citations_common.citationTermGroupList / citations_common.citationTermGroup / childHolder>
{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termSectionTitle"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termVolume"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"termIssue"}, "_owner"=>nil}]}
....

==== children, collapsed, collapsible, name

Description/understanding::
  Typically this is a top level panel in a form.
Treatment detail::
  Same as [.spurious-link]#_*children, name_#

....
<#CspaceConfigUntangler::Forms::Props:5360 core_9-0-0 / collectionobject / default form / panel.collectionobject.reference / reference>
{"name"=>"reference", "collapsible"=>true, "collapsed"=>true, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"referenceGroupList", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"referenceGroup", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"reference"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"referenceNote"}, "_owner"=>nil}]}, "_owner"=>nil}}, "_owner"=>nil}}

<#CspaceConfigUntangler::Forms::Props:5454 core_9-0-0 / collectionobject / default form / panel.collectionobject.rightsin / rightsin>
{"name"=>"rightsin", "collapsible"=>true, "collapsed"=>true, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightsInGroupList", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightsInGroup", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightInTypes", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightInType"}, "_owner"=>nil}}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightInBeginDate"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightInEndDate"}, "_owner"=>nil}]}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"agreementSent"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"agreementReceived"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"agreementSigned"}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightInRestrictions", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightInRestriction"}, "_owner"=>nil}}, "_owner"=>nil}}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightReproductionStatement"}, "_owner"=>nil}}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"rightInNote"}, "_owner"=>nil}]}, "_owner"=>nil}}, "_owner"=>nil}}, "_owner"=>nil}}

<#CspaceConfigUntangler::Forms::Props:5500 core_9-0-0 / collectionobject / default form /  / hierarchy>
{"name"=>"hierarchy", "collapsible"=>true, "collapsed"=>true, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"relation-list-item", "subpath"=>"rel:relations-common-list"}, "_owner"=>nil}}
....

==== name, subpath

Description/understanding::
  Defines a single field with a specified namespace or subpath-based
  override.
Treatment detail::
  Record the namespace and any other overriding info from the subpath

....
<#CspaceConfigUntangler::Forms::Props:4730 materials_4-0-0 / collectionobject / default form / panel.collectionobject.id / objectCount>
{"name"=>"objectCount", "subpath"=>["ns2:collectionobjects_common", "objectCountGroupList", "objectCountGroup", "0"]}

<#CspaceConfigUntangler::Forms::Props:5170 bonsai_6-0-0 / collectionobject / default form / panel.collectionobject.desc / treeType>
{"name"=>"treeType", "subpath"=>"ns2:collectionobjects_bonsai"}

<#CspaceConfigUntangler::Forms::Props:5214 bonsai_6-0-0 / collectionobject / default form / panel.collectionobject.desc / panel.collectionobject.accessionattributes / panel.collectionobject.flowers / flowersJan>
{"name"=>"flowersJan", "subpath"=>"ns2:collectionobjects_accessionattributes"}

<#CspaceConfigUntangler::Forms::Props:14734 herbarium_2-0-12 / loanout / default form / panel.loanout.loanItem / loanoutItems>
{"name"=>"loanoutItems", "subpath"=>"ns2:loansout_naturalhistory_extension"}

<#CspaceConfigUntangler::Forms::Props:14760 herbarium_2-0-12 / taxon / default form / panel.taxon.info / taxonMajorGroup>
{"name"=>"taxonMajorGroup", "subpath"=>"ns2:taxon_herbarium"}
....

==== children, collapsible, name

Description/understanding::
  Typically this is a top level panel in a form.
Treatment detail::
  Same as [.spurious-link]#_*children, name_#

....
<#CspaceConfigUntangler::Forms::Props:5404 core_9-0-0 / conditioncheck / default form / panel.conditioncheck.conditionCheckAndTechAssessmentInfo / conditionCheckAndTechAssessmentInfo>
{"name"=>"conditionCheckAndTechAssessmentInfo", "collapsible"=>true, "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"conditionCheckRefNumber"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"conditionCheckAssessmentDate"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"conditionCheckMethod"}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"conditionCheckReason"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"conditionChecker"}, "_owner"=>nil}]}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"conditionCheckNote"}, "_owner"=>nil}]}

<#CspaceConfigUntangler::Forms::Props:5500 core_9-0-0 / group / default form / panel.group.info / info>
{"name"=>"info", "collapsible"=>true, "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"title"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"responsibleDepartment"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"owner"}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"children"=>{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"groupEarliestSingleDate"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"groupLatestDate"}, "_owner"=>nil}]}, "_owner"=>nil}}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"scopeNote"}, "_owner"=>nil}]}
....

[#children-name-subpath]
==== children, name, subpath

Description/understanding::
  A semantic grouping of fields indicating namespace switch
Treatment detail::
  Same as [.spurious-link]#_*children, name_#, but also record new
  namespace for this level and its descendants

....
<#CspaceConfigUntangler::Forms::Props:7664 anthro_8-0-0 / place / default form / panel.place.consultedDocs / places_nagpra.museumRecordsList / museumRecordsList>
{"name"=>"museumRecordsList", "subpath"=>"ns2:places_nagpra", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"museumRecords"}, "_owner"=>nil}}

<#CspaceConfigUntangler::Forms::Props:7354 anthro_8-0-0 / collectionobject / default form / panel.collectionobject.culturalCare / collectionobjects_culturalcare.accessLimitationsGroupList / accessLimitationsGroupList>
{"name"=>"accessLimitationsGroupList", "subpath"=>"ns2:collectionobjects_culturalcare", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"accessLimitationsGroup", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"limitationType"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"limitationLevel"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"limitationDetails"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"requester"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"requestOnBehalfOf"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"requestDate"}, "_owner"=>nil}]}, "_owner"=>nil}}

<#CspaceConfigUntangler::Forms::Props:6344 publicart_6-0-0 / place / default form / panel.place.info / places_publicart.placementTypes / placementTypes>
{"name"=>"placementTypes", "subpath"=>"ns2:places_publicart", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"placementType"}, "_owner"=>nil}}
....

==== _owner, key, props, ref, type

Description/understanding::
  Same as [.spurious-link]#_*_owner, key, props, ref_#, but with a
  `+type+` key whose value controls something about display.
Treatment detail::
  Because we don't care about display in the data layer, we ignore the
  `+type+` key and treat the same as
  [.spurious-link]#_*_owner, key, props, ref_#

....
<#CspaceConfigUntangler::Forms::Props:5360 anthro_8-0-0 / place / default form /  / propsHolder>
{"type"=>"div", "key"=>nil, "ref"=>nil, "props"=>{"style"=>{"marginTop"=>"10px"}}, "_owner"=>nil}

<#CspaceConfigUntangler::Forms::Props:5404 anthro_8-0-0 / osteology / default form / panel.osteology.info / propsHolder>
{"type"=>"div", "key"=>nil, "ref"=>nil, "props"=>{"style"=>{"marginBottom"=>"8px"}, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"id"=>"form.osteology.default.affirmComplete", "defaultMessage"=>"By checking this box, I am affirming that the inventory of this individual is complete and that any and all unfilled boxes on this form indicate confirmation that those elements (or portions thereof, or features) are not present for this individual.", "values"=>{}}, "_owner"=>nil}}, "_owner"=>nil}
....

==== children, subpath, tabular

Description/understanding::
  A wrapper around a grouping of fields indicating a namespace for the
  grouping, and that the fields are displayed in a table
Treatment detail::
  We treat this like [.spurious-link]#_*children_#, but record the
  namespace for use by its descendants

....
<#CspaceConfigUntangler::Forms::Props:5074 fcart_7-0-0 / conditioncheck / default form / panel.conditioncheck.technicalChanges / childHolder>
{"subpath"=>"ns2:conditionchecks_variablemedia", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"technicalChangesGroupList", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"technicalChangesGroup", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"children"=>{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"technicalChange"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"technicalChangeReason"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"technicalChangeDate"}, "_owner"=>nil}]}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"technicalChangeNote"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"previousSupport"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"newSupport"}, "_owner"=>nil}]}, "_owner"=>nil}]}, "_owner"=>nil}}, "_owner"=>nil}}, "_owner"=>nil}}, "_owner"=>nil}, "tabular"=>false}

<#CspaceConfigUntangler::Forms::Props:5170 publicart_6-0-0 / person / default form / panel.person.info / childHolder>
{"subpath"=>"ns2:persons_publicart", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"socialMediaGroupList", "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"socialMediaGroup", "children"=>[{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"socialMediaHandle"}, "_owner"=>nil}, {"key"=>nil, "ref"=>nil, "props"=>{"name"=>"socialMediaHandleType"}, "_owner"=>nil}]}, "_owner"=>nil}}, "_owner"=>nil}, "tabular"=>false}
....

==== name, showDetachButton

Description/understanding::
  Element for deleting blob from a media record.
Treatment detail::
  We don't need to represent blobs this way in the data layer, so we
  igore these.

....
<#CspaceConfigUntangler::Forms::Props:4730 core_9-0-0 / media / default form /  / blob>
{"name"=>"blob", "showDetachButton"=>true}

<#CspaceConfigUntangler::Forms::Props:4754 bonsai_6-0-0 / media / default form /  / blob>
{"name"=>"blob", "showDetachButton"=>true}
....

==== embedded, label, name

Description/understanding::
  Indicates
  [.spurious-link]#_*Field normally appears in a repeatable field group, but is displayed as a standalone repeatable field in profile_#
  override pattern
Treatment detail::
  Keep parent levels in xpath, since how data is stored does not change.
  Do not record parent levels as part of UI path.

....
<#CspaceConfigUntangler::Forms::Props:4730 materials_4-0-0 / collectionobject / default form / panel.collectionobject.id / collectionobjects_common.materialGroupList / collectionobjects_common.materialGroup / material>
{"name"=>"material", "label"=>"", "embedded"=>true}

<#CspaceConfigUntangler::Forms::Props:4754 materials_4-0-0 / material / default form / panel.material.form / materials_common.formTypeGroupList / materials_common.formTypeGroup / formType>
{"name"=>"formType", "label"=>"", "embedded"=>true}

<#CspaceConfigUntangler::Forms::Props:5000 publicart_6-0-0 / collectionobject / tombstone form / panel.collectionobject.id / collectionobjects_common.titleGroupList / collectionobjects_common.titleGroup / title>
{"name"=>"title", "embedded"=>true, "label"=>""}
....

==== children, name, tabular

Description/understanding::
  Seen in the wrapper of the
  [.spurious-link]#_*Field normally appears in a repeatable field group, but is displayed as a standalone repeatable field in profile_#
  pattern
Treatment detail::
  Treat the same as [.spurious-link]#_*children, name_#. The special
  handling is handled on the child field(s).

....
<#CspaceConfigUntangler::Forms::Props:4730 materials_4-0-0 / collectionobject / default form / panel.collectionobject.id / collectionobjects_common.materialGroupList / collectionobjects_common.materialGroup / materialGroup>
{"name"=>"materialGroup", "tabular"=>false, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"material", "label"=>"", "embedded"=>true}, "_owner"=>nil}}

<#CspaceConfigUntangler::Forms::Props:4754 publicart_6-0-0 / collectionobject / tombstone form / panel.collectionobject.id / collectionobjects_common.objectNameList / collectionobjects_common.objectNameGroup / objectNameGroup>
{"name"=>"objectNameGroup", "tabular"=>false, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"objectName", "embedded"=>true, "label"=>""}, "_owner"=>nil}}

<#CspaceConfigUntangler::Forms::Props:5000 publicart_6-0-0 / collectionobject / tombstone form / panel.collectionobject.desc / collectionobjects_common.materialGroupList / collectionobjects_common.materialGroup / materialGroup>
{"name"=>"materialGroup", "tabular"=>false, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"name"=>"material", "embedded"=>true, "label"=>""}, "_owner"=>nil}}
....

==== style

Description/understanding::
  One-off usage for display styling only
Treatment detail::
  Ignore

....
<#CspaceConfigUntangler::Forms::Props:4040 anthro_8-0-0 / place / default form /  / >
{"style"=>{"marginTop"=>"10px"}}
....

==== children, style

Description/understanding::
  One-off usage for display styling of included elements only
Treatment detail::
  Ignore

....
<#CspaceConfigUntangler::Forms::Props:4040 anthro_8-0-0 / osteology / default form / panel.osteology.info / >
{"style"=>{"marginBottom"=>"8px"}, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"id"=>"form.osteology.default.affirmComplete", "defaultMessage"=>"By checking this box, I am affirming that the inventory of this individual is complete and that any and all unfilled boxes on this form indicate confirmation that those elements (or portions thereof, or features) are not present for this individual.", "values"=>{}}, "_owner"=>nil}}
....

==== defaultMessage, id, values

Used only once. See
[.spurious-link]#_*~defaultMessage~, ~id~, and ~values~_#.

==== children, name, subpath, tabular

===== WHERE name is a namespace and subpath is empty


Currently used once in each of the following profiles:

* ucbg
* ucjeps

In profiles, this is being used to insert locality extension fields into the ns2:collectionobjects_naturalhistory namespace defined by ucbnh-collectionobject extension.

In this application: used to assign children to a namespace, without extracting the `name` value as part of path-to-field (as is usually assumed).

==== children, labelMessage, name

Currently used once in UCJEPS profile.

See <<a1,related Override patterns section>>.

`+labelMessage+` is also covered in <<ruk1,Rarely Used Keys>>.

Untangler treatment: extract message data from `labelMessage`, then treat as <<children-name>>.

==== children, labelMessage, name, subpath

Currently used once in UCJEPS profile.

See <<a1,related Override patterns section>>.

`+labelMessage+` is also covered in <<ruk1,Rarely Used Keys>>.

Untangler treatment: extract message data from `labelMessage`, then treat as <<children-name-subpath>>.

=== Override patterns

==== Field normally appears in a repeatable field group, but is displayed as a standalone repeatable field in profile

*The UI config pattern*

[source,javascript]
----
{
  "key": null,
  "ref": null,
  "props": {
    "name": "materialGroupList",
    "children": {
  "key": null,
  "ref": null,
  "props": {
    "name": "materialGroup",
    "tabular": false,
    "children": {
      "key": null,
      "ref": null,
      "props": {
        "name": "material",
        "label": "",
        "embedded": true
      },
      "_owner": null
    }
  },
  "_owner": null
    }
  },
  "_owner": null
}
----

Usage across all form templates / rectypes/ profiles:

....
<#CspaceConfigUntangler::Forms::Props:4040 materials_4-0-0 / collectionobject / default form / panel.collectionobject.id / collectionobjects_common.materialGroupList / collectionobjects_common.materialGroup / material>
....

The following one is weird because `+formTypeGroupList+` is only defined
for materials/material, and the field "group" contains only one field:
`+formType+`. It seems like this one could follow the normal repeatable
value pattern of `+formTypes/formType+`.

....
<#CspaceConfigUntangler::Forms::Props:4064 materials_4-0-0 / material / default form / panel.material.form / materials_common.formTypeGroupList / materials_common.formTypeGroup / formType>

<#CspaceConfigUntangler::Forms::Props:4110 publicart_6-0-0 / collectionobject / tombstone form / panel.collectionobject.id / collectionobjects_common.titleGroupList / collectionobjects_common.titleGroup / title>

<#CspaceConfigUntangler::Forms::Props:4134 publicart_6-0-0 / collectionobject / tombstone form / panel.collectionobject.id / collectionobjects_common.objectNameList / collectionobjects_common.objectNameGroup / objectName>

<#CspaceConfigUntangler::Forms::Props:4160 publicart_6-0-0 / collectionobject / tombstone form / panel.collectionobject.desc / collectionobjects_common.materialGroupList / collectionobjects_common.materialGroup / material>
....

==== Field normally appears in a repeatable field group, but is displayed as a standalone NON-REPEATABLE field in profile

Used once across everything:

....
<#CspaceConfigUntangler::Forms::Props:4730 materials_4-0-0 / collectionobject / default form / panel.collectionobject.id / objectCount>
{"name"=>"objectCount", "subpath"=>["ns2:collectionobjects_common", "objectCountGroupList", "objectCountGroup", "0"]}
....

[#a1]
==== Normally appears as a panel (collapsible main grouping of fields), but make it appear as a normal field grouping

Used once in UCJEPS:

[source,javascript]
----
"props": {
  "name": "referenceGroup",
  "labelMessage": {
    "id": "field.collectionobjects_common.referenceGroup.name",
    "defaultMessage": "Reference"
  },
  "children": [
    {
      "key": null,
      "ref": null,
      "props": {
        "name": "reference"
      },
      "_owner": null
    },
    {
      "key": null,
      "ref": null,
      "props": {
        "name": "referenceNote"
      },
      "_owner": null
    }
  ]
}
----

Used once in UCJEPS:

[source,javascript]
----
"props": {
  "name": "localityGroupList",
  "subpath": "ns2:collectionobjects_naturalhistory",
  "labelMessage": {
    "id": "field.collectionobjects_naturalhistory.localityGroup.name",
    "defaultMessage": "Locality"
  },
  "children": {
    ...lots of fields...
  }
}
----


=== Rarely used keys

==== `+embedded+`

Currently used only in the
[.spurious-link]#_*Field normally appears in a repeatable field group, but is displayed as a standalone repeatable field in profile_#
override.

==== `+defaultMessage+`, `+id+`, and `+values+`

anthro_8-0-0 / osteology / default form / panel.osteology.info /
nonamelevel has:

[source,javascript]
----
"props":{"children": [
              {
                "key": null,
                "ref": null,
                "props": {
                  "name": "InventoryIsComplete"
                },
                "_owner": null
              },
              {
                "type": "div",
                "key": null,
                "ref": null,
                "props": {
                  "style": {
                    "marginBottom": "8px"
                  },
                  "children": {
                    "key": null,
                    "ref": null,
                    "props": {
                      "id": "form.osteology.default.affirmComplete",
                      "defaultMessage": "By checking this box, I am affirming that the inventory of this individual is complete and that any and all unfilled boxes on this form indicate confirmation that those elements (or portions thereof, or features) are not present for this individual.",
                      "values": {
                      }
                    },
                    "_owner": null
                  }
                },
                "_owner": null
              },
              # ...
            ]}
----

`+props/children/1/children+` contains the sole uses of the
`+defaultMessage+`, `+id+`, and `+values+` keys across all forms for all
record types for all profiles.

I'm interpreting this whole node as forcing display of the "By checking
this box…" `+defaultMessage+` under the `+InventoryIsComplete+` checkbox
element. Since this is not actually part of the data layer, I'm ignoring
it.

==== `+showDetachButton+`

Currently only used in
`+media / panel.media.media / panel.media.file / blob+`, with the
following `+props+` object, which is ignored by the Untangler:

[source,javascript]
----
{"name"=>"blob", "showDetachButton"=>true}
----

[#ruk1]
==== `+labelMessage+`

Used twice in UCJEPS collectionobject collectorLabel form. Used to label the child fields as a field group. (In the default form, the child fields appear as collapsible panels)

==== `+style+`

This key is used only twice across all forms for all rectypes for all
profiles:

....
<#CspaceConfigUntangler::Forms::Form:4040
  id: anthro_8-0-0 place default
  disabled?: false
  fields: 46>
<#CspaceConfigUntangler::Forms::Props:4064 anthro_8-0-0 / place / default form /  / >
{"style"=>{"marginTop"=>"10px"}}


<#CspaceConfigUntangler::Forms::Form:4110
  id: anthro_8-0-0 osteology default
  disabled?: false
  fields: 23>
<#CspaceConfigUntangler::Forms::Props:4134 anthro_8-0-0 / osteology / default form / panel.osteology.info / >
{"style"=>{"marginBottom"=>"8px"}, "children"=>{"key"=>nil, "ref"=>nil, "props"=>{"id"=>"form.osteology.default.affirmComplete", "defaultMessage"=>"By checking this box, I am affirming that the inventory of this individual is complete and that any and all unfilled boxes on this form indicate confirmation that those elements (or portions thereof, or features) are not present for this individual.", "values"=>{}}, "_owner"=>nil}}
....

As this pertains only to the data layer, I am ignoring it.

=== Always empty keys

Currently, the following keys are always null:

* key
* ref
* _owner

=== Subpath values used

The Untangler currently ignores `+rel:relations-common-list+` values.

It checks for subpath values that are Arrays instead of Strings, because
apparently those are going to be weird.

....
93  rel:relations-common-list
58  ns2:collectionobjects_accessionattributes
41  ns2:claims_nagpra
13  ns2:loansout_botgarden
12  ns2:osteology_anthropology
12  ns2:collectionobjects_herbarium
11  ns2:collectionobjects_botgarden
10  ns2:collectionobjects_bonsai
10  ns2:collectionobjects_annotation
9   ns2:conservation_publicart
9   ns2:conservation_livingplant
9   ns2:loansin_herbarium
8   ns2:places_nagpra
8   ns2:collectionobjects_nagpra
8   ns2:collectionobjects_naturalhistory_extension
8   ns2:loansout_herbarium
7   ns2:collectionobjects_fineart
7   ns2:intakes_lhmc
6   ns2:collectionobjects_publicart
6   ns2:collectionobjects_anthro
6   ns2:persons_lhmc
6   ns2:collectionobjects_materials
5   ns2:loansout_naturalhistory_extension
4   ns2:conditionchecks_lhmc
4   ns2:collectionobjects_culturalcare
4   ns2:places_publicart
4   ns2:collectionobjects_variablemedia
4   ns2:movements_botgarden
4   ns2:taxon_herbarium
3   ns2:organizations_publicart
3   ns2:locations_publicart
3   ns2:acquisitions_commission
3   ns2:concepts_fineart
2   ns2:persons_publicart
2   ns2:loansin_naturalhistory_extension
2   ns2:valuationcontrols_publicart
2   ns2:media_publicart
2   ns2:conservation_bonsai
2   ns2:places_lhmc
2   ns2:acquisitions_publicart
1   ns2:media_materials
1   ["ns2:collectionobjects_common", "objectCountGroupList", "objectCountGroup", "0"]
1   ns2:conditionchecks_variablemedia
1   ns2:objectexit_naturalhistory_extension
1   ns2:acquisitions_lhmc
1   ns2:collectionobjects_accessionuse
1   ns2:exhibitions_lhmc
1   ns2:loansin_lhmc
1   ns2:loansout_lhmc
1   ns2:movements_lhmc
1   ns2:groups_checklist
1   ns2:exhibitions_publicart
1   ns2:conditionchecks_publicart
....

== Messages

This section is about messageable data elements.

messageable data element:: a data-relevant element of CollectionSpace with which a message or label is associated in the CollectionSpace UI.

There are many other message categories, but most of them are for interactive elements in the UI (buttons, error messages, search options, etc.)

Option list values are just specific messages, but they are not covered here either, as the Untangler treats them as possible field values, not messageable data elements.

There's https://github.com/collectionspace/cspace-ui.js/blob/master/docs/configuration/messages.js[a page in the cspace-ui.js documentation folder] that lists "all messages used in cspace-ui, to be used as a reference for customization or translation." However, it does not appear to contain messages for non-core UI plugins, and I'm not sure if/how it is maintained.

=== Message definition in `recordType` objects
Varies per type of element for which a message is being defined.

==== columns - element_type.rec_type.column_type.field_name

In `recordTypes/#{recordType}/columns/#{columnsdef}`:

....
"objectNumber": {
  "messages": {
    "label": {
      "id": "column.collectionobject.default.objectNumber",
      "defaultMessage": "Identification number"
    }
  },
  "order": 10,
  "sortBy": "collectionobjects_common:objectNumber",
  "width": 200
},
....

==== field - element_type.namespace.field_name.message_type

In `recordTypes/#{recordType}/fields/document/#{namespace}/`, where exact nesting level depends on whether field is part of group.:

....
"annotationType": {
  "[config]": {
    "messages": {
      "fullName": {
        "id": "field.collectionobjects_annotation.annotationType.fullName",
        "defaultMessage": "Annotation type"
      },
      "name": {
        "id": "field.collectionobjects_annotation.annotationType.name",
        "defaultMessage": "Type"
      }
    },
    "view": {
      "type": "TermPickerInput",
      "props": {
        "source": "annotationtype"
      }
    }
  }
},
....

Note that "fields" that indicate a field grouping (not an actual field containing values) are also defined this way:

....
"annotationGroup": {
  "[config]": {
    "messages": {
      "name": {
        "id": "field.collectionobjects_annotation.annotationGroup.name",
        "defaultMessage": "Annotation"
      }
    },
    "repeating": true,
    "view": {
      "type": "CompoundInput"
    }
  },
-fields defined-
},
....

==== inputTable - element_type.rec_type.field_name

inputTable:: Appears to be a (the?) mechanism for making non-repeatable, non-grouped fields display in the UI as a field group.

In `recordTypes/#{recordType}/messages/inputTable`:

....
"age": {
  "id": "inputTable.collectionobject.age",
  "defaultMessage": "Age"
},
"assocEvent": {
  "id": "inputTable.collectionobject.assocEvent",
  "defaultMessage": "Associated event"
},
....

==== panel - element_type.rec_type.panel_name

In `recordTypes/#{recordType}/messages/panel`:

....
"id": {
  "id": "panel.collectionobject.id",
  "defaultMessage": "Object Identification Information"
},
"desc": {
  "id": "panel.collectionobject.desc",
  "defaultMessage": "Object Description Information"
},
....

==== record - element_type.rec_type.message_type

In `recordTypes/#{recordType}/messages/record`:

....
"name": {
  "id": "record.collectionobject.name",
  "defaultMessage": "Object"
},
"collectionName": {
  "id": "record.collectionobject.collectionName",
  "defaultMessage": "Objects"
}
....

==== vocab - element_type.authority_name.vocab_name.message_type

In authority record types only, in `recordTypes/#{recordType}/vocabularies`:

....
"local": {
  "messages": {
    "name": {
      "id": "vocab.citation.local.name",
      "defaultMessage": "Local"
    },
    "collectionName": {
      "id": "vocab.citation.local.collectionName",
      "defaultMessage": "Local Citations"
    },
    "itemName": {
      "id": "vocab.citation.local.itemName",
      "defaultMessage": "Local Citation"
    }
  },
  "serviceConfig": {
    "servicePath": "urn:cspace:name(citation)"
  },
  "sortOrder": 0,
  "name": "local",
  "disableAltTerms": false
},
....

=== Known message types

name:: field, record, vocab
fullName:: field
collectionName:: record, vocab
itemName:: vocab
no message type - type is name of messaged element:: inputTable, panel
no message type - other:: column

=== Profile-level overrides

Any type of messagable element can be overridden at the profile level. Example from botgarden profile, top level of config JSON:

....
"messages": {
    "about.title": "Welcome to CollectionSpace: Botanical Garden",
    "panel.collectionobject.collect": "Field Collection Information",
    "column.loanout.default.borrower": "Institution",
    "field.collectionobjects_common.objectNumber.name": "Accession number",
    "field.collectionobjects_common.recordStatus.name": "Provenance data quality",
    "field.collectionobjects_common.briefDescription.name": "Material type",
    "field.collectionobjects_common.comment.name": "Accession note",
    "field.collectionobjects_common.fieldCollectionNote.name": "Habitat information",
    "record.loanout.name": "Voucher",
    "record.loanout.collectionName": "Vouchers",
    "panel.loanout.info": "Voucher Information",
    "field.loansout_common.loanOutNumber.name": "Voucher collection number",
},
....

Such overrides must be overlaid on whatever messages have been extracted from individual record types before processing.
