#!/usr/bin/env ruby
# frozen_string_literal: true

# If we're loading from source instead of a gem, rubygems
# isn't setting load paths for us, so we need to set it ourselves
self_load_path = File.expand_path("../lib", File.dirname(__FILE__))
is_gem = self_load_path["/gems/"] ? true : false
$LOAD_PATH << self_load_path unless is_gem ||
  $LOAD_PATH.include?(self_load_path)
require "cspace_config_untangler"

CCU::Cli::TopCli.start(ARGV)
